try:
    #código que pode causar um erro
    resultando = 10 / 0
except:
    # código que trata o erro
    print("ocorreu um erro durante a operaçao!")